### ISSUE TITLE
error when building master on Alpine Linux

### ISSUE THREAD

**Issue by axelu** [h2o/h2o#2322]
Trying to build master on Alpine (Alpine latest stable 3.11).
```
[ 29%] Building C object CMakeFiles/h2o-httpclient.dir/src/httpclient.c.o
/home/axel/h2o/src/httpclient.c:25:10: fatal error: execinfo.h: No such file or directory
   25 | #include <execinfo.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```
Alpine with musl-libc does not provide such a header by default. Maybe prudent to make it a conditional.
To get over the error for now, I added libexecinfo-dev package via apk, but I am not sure that is the correct approach. I found a similar issue referenced [here](https://github.com/awslabs/aws-c-common/issues/322).

Adding libexecinfo-dev package via apk gets me over the missing execinfo.h error, but the next error then is:
```
[29%] Linking C executable h2o-httpclient
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: libh2o-evloop.so.0.16.0-DEV: undefined reference to `BrotliEncoderCompress'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: libh2o-evloop.so.0.16.0-DEV: undefined reference to `BrotliDecoderDecompress'
collect2: error: ld returned 1 exit status
```

How to link to Brotli to get over this error?

invocation and output of cmake:

```
$ cmake -B build . -DCMAKE_BUILD_TYPE=None -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_LIBDIR=/usr/lib -DCMAKE_INSTALL_PREFIX=/usr -DWITH_MRUBY=ON
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.3") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.1.1g")  
-- Found ZLIB: /lib/libz.so (found version "1.2.11") 
-- Performing Test ARCH_SUPPORTS_64BIT_ATOMICS
-- Performing Test ARCH_SUPPORTS_64BIT_ATOMICS - Success
-- Performing Test HAS_PTHREAD_SETAFFINITY_NP
-- Performing Test HAS_PTHREAD_SETAFFINITY_NP - Success
-- Performing Test LIBC_HAS_BACKTRACE
-- Performing Test LIBC_HAS_BACKTRACE - Success
-- Detecting USDT support
-- Detecting USDT support - not found
-- Checking for module 'libuv>=1.0.0'
--   Found libuv, version 1.34.0
-- Checking for module 'libwslay'
--   Found libwslay, version 1.1.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/axel/h2o/build
```

**Comment by axelu** [comment]
@syohex Your changes in #2326 fix this issue, hence the PR/MR should be accepted.

**Comment by syohex** [comment]
I think this issue has been already fixed.

**Comment by vpeter4** [comment]
Seems this issue is still present in git master:
```
[100%] Linking C executable h2o-httpclient
libh2o-evloop.so.0.16.0-DEV: undefined reference to `BrotliEncoderCompress'
libh2o-evloop.so.0.16.0-DEV: undefined reference to `BrotliDecoderDecompress'
```

How to fix this?
