### ISSUE TITLE
Server crashes if the OCSP Response is Unkown

### ISSUE THREAD

**Issue by firegore** [h2o/h2o#371]
Greetings,

i created a new Cert, if the OCSP Response is unknown, the Servers crashes

Jun 19 21:29:51 web.firegore.com h2o[14881]: [OCSP Stapling] successfully updated the response for certificate file:(null)
Jun 19 21:29:51 web.firegore.com h2o[14881]: received fatal signal 11; backtrace follows
Jun 19 21:29:51 web.firegore.com h2o[14881]: /usr/bin/h2o[0x4401c6] yaml_emitter_flush at ??:?
Jun 19 21:29:51 web.firegore.com h2o[14881]: /usr/lib/libpthread.so.0(+0x10660)[0x7fba507fa660] ?? ??:0
Jun 19 21:29:51 web.firegore.com h2o[14881]: /usr/bin/h2o(h2o_configurator_get_cmd_path+0x4)[0x414ef4] h2o_configurator_get_cmd_path at ??:?
Jun 19 21:29:51 web.firegore.com h2o[14881]: /usr/bin/h2o[0x43f9fb] yaml_emitter_flush at ??:?
Jun 19 21:29:51 web.firegore.com h2o[14881]: verify OK (used: -VAfile /tmp/Sl4WTDeqdB/issuer.crt)
Jun 19 21:29:51 web.firegore.com h2o[14881]: /usr/bin/h2o[0x43fba5] yaml_emitter_flush at ??:?
Jun 19 21:29:51 web.firegore.com h2o[14881]: /usr/lib/libpthread.so.0(+0x7354)[0x7fba507f1354] ?? ??:0
Jun 19 21:29:51 web.firegore.com h2o[14881]: verifying the response signature
Jun 19 21:29:51 web.firegore.com h2o[14881]: /etc/ssl/anotherworkingcert.crt: good
Jun 19 21:29:51 web.firegore.com h2o[14881]: This Update: Jun 19 19:23:25 2015 GMT
Jun 19 21:29:51 web.firegore.com h2o[14881]: Next Update: Jun 21 19:23:25 2015 GMT
Jun 19 21:29:51 web.firegore.com h2o[14881]: verifying the response signature
Jun 19 21:29:51 web.firegore.com h2o[14881]: /etc/ssl/workingcert.crt: good
Jun 19 21:29:51 web.firegore.com h2o[14881]: This Update: Jun 19 19:23:25 2015 GMT
Jun 19 21:29:51 web.firegore.com h2o[14881]: Next Update: Jun 21 19:23:25 2015 GMT
Jun 19 21:29:51 web.firegore.com h2o[14881]: verifying the response signature
Jun 19 21:29:51 web.firegore.com h2o[14881]: verify OK (used: -VAfile /tmp/WE8i7Teoun/issuer.crt)
Jun 19 21:29:51 web.firegore.com h2o[14881]: verify OK (used: -VAfile /tmp/nSLJWXB3c0/issuer.crt)
Jun 19 21:29:51 web.firegore.com h2o[14881]: verify OK (used: -VAfile /tmp/iN8x7SUyex/issuer.crt)
Jun 19 21:29:51 web.firegore.com h2o[14881]: /etc/ssl/ocspunknown.crt: unknown
Jun 19 21:29:51 web.firegore.com h2o[14881]: This Update: Jun 19 19:23:25 2015 GMT
Jun 19 21:29:51 web.firegore.com h2o[14881]: Next Update: Jun 21 19:23:25 2015 GMT

i think this isnt the right way to handle that

$ h2o -v                                                                                                                                                                                                    
h2o version 1.3.0

**Comment by kazuho** [comment]
Thank you for reporting the issue.  Looking at the log it seems that the server process itself is crashing before the OCSP stapling status of `ocspunknown.crt` is resolved to be `unknown` by a sub-process dedicated to the task.

Question 1. Do you still have any lines above the first lines of the log?

> Jun 19 21:29:51 web.firegore.com h2o[14881]: [OCSP Stapling] successfully updated the response for certificate file:(null)
> Jun 19 21:29:51 web.firegore.com h2o[14881]: received fatal signal 11; backtrace follows

Things seem to be already going wrong in the first line, certificate file (extracted from the configuration file) should not become NULL; it being emitted as `(null)` is strange.

Question 2. What command line arguments did you use to invoke the h2o command?

Question 3. What do you see if you run H2O using the `-m test` configuration option?  It would just test the configuration (as well as OCSP stapling results) and exit.  It would be great if you could provide the full output so that we could diagnose the issue if something seems wrong.

**Comment by firegore** [comment]
1. Full Log Here: https://gist.github.com/firegore/91bb5d9c1e61a182b515

I tried it now, just to be sure, the OCSP Responders now know the new Certificate, so it isnt unknown anymore. but as soon as i include the www.firegore.com.combined Cert the Server crashes, the other ones work fine, 

2. /usr/bin/h2o --mode master --conf /etc/h2o.conf

3. Output of h2o -m test: https://gist.github.com/firegore/a44db0290e81533c7636

PS: the Cert that was previously know as ocspunknown is the www.firegore.com.combined

**Comment by firegore** [comment]
UPDATE: i tried it with separating the different vhosts (have about 6 of them). 

So far it only happend with RSA 4096 Bit Keys and SHA2 Certs

If i remove some of the Vhosts, the Server doesn't crash anymore, and even the before not working Certificate is working, but now one of my other Certs stopped working.

It starts working when i only have about 4 -5 Certs in my h2o.conf, maybe the register or something isnt big enough for that amount of Certs?

Sry i'm a noob regarding programming, just a NetworkServerAdmin who wants to get the most out of his Infrastructure

I'm using h2o as a Frontend for an Nginx Webserver

OpenSSL 1.0.2b 11 Jun 2015 with ChaCha20Poly Support
Host is running ArchLinux with gcc5.1 and glibc 2.21

**Comment by kazuho** [comment]
Thank the information.  It helps a lot!

Reading your notes, I agree that the issue is likely related to the number of certificates being used.

Will check if I can reproduce the issue.

**Comment by firegore** [comment]
Thanks for your Help.

I tried the Workaroung with OCSP Stapling disabled. The Server starts fine, but as soon as you load the Page or a Connection arrives the Server crashes

Crash Log:
https://gist.github.com/firegore/761f788257bce2d3ab82

**Comment by kazuho** [comment]
> I tried the Workaroung with OCSP Stapling disabled. The Server starts fine, but as soon as you load the Page or a Connection arrives the Server crashes

Thank you for trying.  I succeeded in reproducing the crash as well.

I expect that the bug has been fixed in #375 but do not have enough time to check until I come back later this week.  I would appreciate it if you could try the code and see what happens.

**Comment by firegore** [comment]
i compiled straight from git, still not working

The Interesting thing is, if i connect with the CLI or with a Browser to one of my Hostnames, the h2o Worker crashes, if i connect through the other hostnames, it dont crashes, but its also not delivering any content

**Comment by kazuho** [comment]
@firegore Sorry for my late response.

> i compiled straight from git, still not working

Did you try the `kazuho/issues/371` branch?  The fix to be tested was not merged to master at the moment I asked for you to test.

Today I have tested the fix with 6 certificates and it seems to work fine, therefore I have merged the changes to master.

I would appreciate it if you could verify if the issue still exists by using the master branch.  Thank you in advance.
